### ISSUE TITLE
The set of supported materials

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#10]
Thanks for your excellent work. Do you only support the 40 materials (40 sbs files) in the folder 'diffmat/test/sbs/match_v1'?

**Comment by Polar1s** [comment]
Hey there! We do support more materials than the ones provided as long as they conform to the limitations mentioned in README. Unfortunately, we aren't allowed to release the other materials used in the paper due to copyright restrictions (they are proprietary to Adobe). However, you can download various artist-created procedural materials from Adobe Substance 3D Assets via paid subscription.

I wish you all the best luck with your project!

**Comment by HospitableHost** [comment]
I found that all the materials available for free in the S3D community are in sbsar file format and cannot be used in this project. So do you know where to find free sbs files? Or is there any way to restore the sbsar file back to the sbs file?

**Comment by Polar1s** [comment]
Substance 3D Assets does have SBS materials. I'm not aware of any other free SBS dataset online, unfortunately. You can try working around it depending on your goal. For instance, subscription will be less of a concern if you just run optimizations case by case using the monthly download quota. If you need many materials for machine learning, however, it'd be better to get internal access through employment or collaboration with Adobe.
