### ISSUE TITLE
the installation of Substance 3D Automation Tookit

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#5]
Thanks for your good work. It's amazing so I want to follow it. But I have some trouble installing the AS3D or SAT.
Is it necessary or optional to install the AS3D and SAT?
If it is necessary, how about just install SAT? (AS3D seems not free)
How to install SAT? I just can find the installation of Pysbs in (https://helpx.adobe.com/substance-3d-sat/pysbs-python-api/getting-started.html) which seems not related to sbscooker and sbsrender.
Thanks for your reply.

**Comment by Polar1s** [comment]
Hi. Thanks for trying out the library! Either AS3D or SAT will work since DiffMat only uses two executables that ship with the software (sbscooker and sbsrender) to generate input textures externally.

SAT used to be available by subscription before Adobe acquired Substance but it's a different story now. Therefore, simply install AS3D from Adobe Creative Cloud and you should be good. Provide your custom installation path of AS3D if DiffMat has trouble locating the executables.

**Comment by JINNMnm** [comment]
Is AS3D available on linux? I start my free trail as a student but can't find a available installer for linux.
