### ISSUE TITLE
sbs file missing

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#7]
I noticed that the input parameter is required: `parser.add_argument('input', metavar='FILE', help='Path to the input *.sbs file')`
But your paper use a database of procedural materials, and use a special method to search a procedural material. So where is the database and the code of searching? 
Sorry to bother you, I'm new to this research field.
Thanks to your reply, best wishes to your research.

**Comment by Polar1s** [comment]
The results in the paper were produced using materials in the Adobe Substance 3D Assets repository, which unfortunately cannot be distributed on GitHub due to their proprietary nature. That said, you can download a limited number of assets from the Substance Assets repo based on subscription.

DiffMat focuses on node parameter optimization for predefined graph structures so material search is not included. I apologize if this poses any limitation to your use case. Method-wise, we inherited the nearest neighbor search algorithm from MATch [Shi et al., SIGGRAPH Asia 2020], and it should be relatively straightforward to implement based on DiffMat's `TextureDescriptor` class.

Alternatively, you may take a look at the latest methods (MatFormer [Guerrero et al., SIGGRAPH 2022] and its follow-up [Hu et al., SIGGRAPH 2023]) that predict the material graph structure from the input image.

Wish you all the best with research. Cheers.
